project:
  type: website
  output-dir: ../_site/ai-learning-circle/
  render:
    - slides/**

format:
  revealjs:
    theme: simple
    highlight-style: github
    incremental: true
    css:
      - ../styles/base.scss
      - ../styles/ai-learning-circle.scss
    toc: true


filters:
  - ../filters/ai-learning-circle/specific.lua
  - ../filters/global/reveal-tweaks.lua
  - ../filters/global/speaker-notes.lua